### ISSUE TITLE
Custom key initialization

### ISSUE THREAD

**Issue by soyuka** [joehand/dat-node-deprecated#8]
Hi,

I'm trying to initialize a new `Dat` instance with a custom key, but it seems to silently fail somewhere. Is this possible? 

For example:

```
// rm -r .dat
let d = new Dat({
  dir: process.cwd(),
  key: 'c320479b2849b46b8cc9b88e5afa41de2643618746708c72ae1b3064591dc8fb'
})

d.share(function(err) {
  if (err) {
    throw err
  }
  console.log('Directory shared')
})
```

Still, if I use the script without key on initialization, I get a key, for example `8b6d22282a19d8ddcea05f54fe1c9cf503a31d38f27aa9eb8e4dd662ef780457`. Then I'm able to initialize the `Dat` with the given key and share the same directory on the same key. 

Maybe related to https://github.com/datproject/discussions/issues/55.

**Comment by joehand** [comment]
Hi @soyuka, 

`dat.share()` assumes you are creating the archive and own the archive (meaning you can write to it). To initialize it with a specific key, you have to already have the database locally and pass that as the dir option, is that what you are doing? Otherwise it will (silently & poorly) fail and create an archive with a different key.

If you are trying to download a remote archive, try `dat.download()`. 

PS. This repo moved back to [datproject/dat-node](https://github.com/datproject/dat-node), sorry for any confusion.

**Comment by soyuka** [comment]
> silently & poorly

:p I like that.

I need to study a bit more my needs before I can really make a use case but my main goal here was just to have a custom-made key (ie not random). Thanks for the quick answer, I'll reopen this in the new repository if needed. Btw, do you guys have a roadmap of some sort (when should `dat-node` be used instead of `datjs`? ie when will the main command line repository be `dat-node` dependent?). 

Okay nevermind found the answer https://github.com/datproject/dat/commit/cd341a4cbdd82ddff3b824342a927bd727fd3c28 !

**Comment by joehand** [comment]
> I need to study a bit more my needs before I can really make a use case but my main goal here was just to have a custom-made key (ie not random)

Ya I'm don't think this is currently possible with hyperdrive. I *think* there would be some security issues with that, so it may not be in the plans either.

> when will the main command line repository be dat-node dependent?

You got it! `dat-node === dat-js`.

**Comment by soyuka** [comment]
But dat-js was meant to run in the browser no? Finally it can't so it has been deprecated? I think I've read some things like that in some of the issues. Anyway, now we should use dat-node, good to know !

**Comment by joehand** [comment]
> But dat-js was meant to run in the browser no.

We weren't sure at first but I made it with a big focus on what we needed for the CLI. Since that diverged a lot we decided it'd be easier if they're separate.
